package com.bsstokes.learnanything.api.models;

public class Exercise {
    // translated_short_display_name: "Finding abs",
    // uses_streak_selection: false,
    // v_position: 5,
    // relative_url: "/exercise/absolute_value",
    // guaranteed_file_name: "absolute_value.html",
    // file_name: "absolute_value.html",
    // related_video_readable_ids: [
    //         "absolute-value-and-number-lines",
    //         "absolute-value-1",
    //         "absolute-value-of-integers"
    //         ],
    // author_name: "Marcia Lee",
    // creation_date: "2014-12-30T19:12:13Z",
    // uses_assessment_items: false,
    public String ka_url;
    // short_display_name: "Finding abs",
    // translated_title: "Finding absolute values",
    // author_key: "ag5zfmtoYW4tYWNhZGVteXJaCxIIVXNlckRhdGEiTHVzZXJfaWRfa2V5X2h0dHA6Ly9ub3VzZXJpZC5raGFuYWNhZGVteS5vcmcvNjZmOTNhODE4YjU2ZWUxZTliOTM1MGI2OTc2OGQ4ZTMM",
    // translated_description_html: "Find the absolute value of a given number.",
    public String id; // "12293397",
    // is_quiz: false,
    // display_name: "Finding absolute values",
    // tracking_document_url: "https://docs.google.com/a/khanacademy.org/open?id=1t5VsA_D7asQJHVYsFQ3cpKTRdlf3tVuRRvyoXu2Cqqo",
    // description_html: "Find the absolute value of a given number.",
    // do_not_publish: false,
    // tags: [ ],
    // progress_key: "e12293397",
    // suggested_completion_criteria: "num_correct_in_a_row_5",
    // edit_slug: "edit/e/12293397",
    // summative: false,
    // live: true,
    public String translated_description; // "Find the absolute value of a given number.",
    // pretty_display_name: "Finding absolute values",
    // deleted_mod_time: "2013-07-13T00:03:08Z",
    // all_assessment_items: [ ],
    // description: "Find the absolute value of a given number.",
    public String translated_pretty_display_name; // "Finding absolute values",
    // node_slug: "e/absolute_value",
    // deleted: false,
    // uses_worked_examples: false,
    // backup_timestamp: "2013-09-29T10:12:20Z",
    // problem_types: [ ],
    // curated_related_videos: [
    //         "2344592",
    //         "26784",
    //         "13179307"
    //         ],
    // covers: [ ],
    // h_position: 34,
    // translated_display_name: "Finding absolute values",
    // kind: "Exercise",
    // sha1: "0fb4332b7167dc5c61722440c9cd68beedf3a4a0",
    // name: "absolute_value",
    // date_modified: "2014-12-30T19:20:08Z",
    // prerequisites: [
    //         "number-opposites"
    //         ],
    // assessment_item_tags: [
    //         "ag5zfmtoYW4tYWNhZGVteXIxCxIRQXNzZXNzbWVudEl0ZW1UYWciATAMCxIRQXNzZXNzbWVudEl0ZW1UYWcYofUNDA",
    //         "ag5zfmtoYW4tYWNhZGVteXIxCxIRQXNzZXNzbWVudEl0ZW1UYWciATAMCxIRQXNzZXNzbWVudEl0ZW1UYWcY6Z4iDA",
    //         "ag5zfmtoYW4tYWNhZGVteXI2CxIRQXNzZXNzbWVudEl0ZW1UYWciATAMCxIRQXNzZXNzbWVudEl0ZW1UYWcYgICAwIKTqAoM"
    //         ],
    // title: "Finding absolute values",
    // global_id: "e12293397",
    // seconds_per_fast_problem: 4,
    // sha: "64284421902ac50b854241d9485e0304157f54da",
    public String image_url; // "https://ka-exercise-screenshots.s3.amazonaws.com/absolute_value.png",
    // tutorial_only: false,
    // current_revision_key: "64284421902ac50b854241d9485e0304157f54da",
    public String image_url_256; // "https://ka-exercise-screenshots.s3.amazonaws.com/absolute_value_256.png",
    // content_id: "12293397",
    // content_kind: "Exercise"
}
